// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: internal/shared/proto/shikimori.proto

package shikimori

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShikimoriService_GetAnimeInfo_FullMethodName = "/shikimori.ShikimoriService/GetAnimeInfo"
)

// ShikimoriServiceClient is the client API for ShikimoriService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ShikimoriService — сервис для получения информации об аниме с Shikimori.one (GraphQL)
type ShikimoriServiceClient interface {
	// GetAnimeInfo — ищет аниме по строке (название/ромадзи/русское) и возвращает первую подходящую запись
	GetAnimeInfo(ctx context.Context, in *GetAnimeInfoRequest, opts ...grpc.CallOption) (*GetAnimeInfoResponse, error)
}

type shikimoriServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShikimoriServiceClient(cc grpc.ClientConnInterface) ShikimoriServiceClient {
	return &shikimoriServiceClient{cc}
}

func (c *shikimoriServiceClient) GetAnimeInfo(ctx context.Context, in *GetAnimeInfoRequest, opts ...grpc.CallOption) (*GetAnimeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnimeInfoResponse)
	err := c.cc.Invoke(ctx, ShikimoriService_GetAnimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShikimoriServiceServer is the server API for ShikimoriService service.
// All implementations must embed UnimplementedShikimoriServiceServer
// for forward compatibility.
//
// ShikimoriService — сервис для получения информации об аниме с Shikimori.one (GraphQL)
type ShikimoriServiceServer interface {
	// GetAnimeInfo — ищет аниме по строке (название/ромадзи/русское) и возвращает первую подходящую запись
	GetAnimeInfo(context.Context, *GetAnimeInfoRequest) (*GetAnimeInfoResponse, error)
	mustEmbedUnimplementedShikimoriServiceServer()
}

// UnimplementedShikimoriServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShikimoriServiceServer struct{}

func (UnimplementedShikimoriServiceServer) GetAnimeInfo(context.Context, *GetAnimeInfoRequest) (*GetAnimeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnimeInfo not implemented")
}
func (UnimplementedShikimoriServiceServer) mustEmbedUnimplementedShikimoriServiceServer() {}
func (UnimplementedShikimoriServiceServer) testEmbeddedByValue()                          {}

// UnsafeShikimoriServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShikimoriServiceServer will
// result in compilation errors.
type UnsafeShikimoriServiceServer interface {
	mustEmbedUnimplementedShikimoriServiceServer()
}

func RegisterShikimoriServiceServer(s grpc.ServiceRegistrar, srv ShikimoriServiceServer) {
	// If the following call panics, it indicates UnimplementedShikimoriServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShikimoriService_ServiceDesc, srv)
}

func _ShikimoriService_GetAnimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShikimoriServiceServer).GetAnimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShikimoriService_GetAnimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShikimoriServiceServer).GetAnimeInfo(ctx, req.(*GetAnimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShikimoriService_ServiceDesc is the grpc.ServiceDesc for ShikimoriService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShikimoriService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shikimori.ShikimoriService",
	HandlerType: (*ShikimoriServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnimeInfo",
			Handler:    _ShikimoriService_GetAnimeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/shared/proto/shikimori.proto",
}
