// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/shared/proto/shikimori.proto

package shikimori

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAnimeInfoRequest struct {
	Search               string   `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnimeInfoRequest) Reset()         { *m = GetAnimeInfoRequest{} }
func (m *GetAnimeInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnimeInfoRequest) ProtoMessage()    {}
func (*GetAnimeInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4d8bf40730cdee, []int{0}
}

func (m *GetAnimeInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimeInfoRequest.Unmarshal(m, b)
}
func (m *GetAnimeInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimeInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetAnimeInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimeInfoRequest.Merge(m, src)
}
func (m *GetAnimeInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnimeInfoRequest.Size(m)
}
func (m *GetAnimeInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimeInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimeInfoRequest proto.InternalMessageInfo

func (m *GetAnimeInfoRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type GetAnimeInfoResponse struct {
	// Types that are valid to be assigned to Result:
	//	*GetAnimeInfoResponse_Anime
	//	*GetAnimeInfoResponse_Error
	Result               isGetAnimeInfoResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetAnimeInfoResponse) Reset()         { *m = GetAnimeInfoResponse{} }
func (m *GetAnimeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetAnimeInfoResponse) ProtoMessage()    {}
func (*GetAnimeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4d8bf40730cdee, []int{1}
}

func (m *GetAnimeInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimeInfoResponse.Unmarshal(m, b)
}
func (m *GetAnimeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimeInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetAnimeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimeInfoResponse.Merge(m, src)
}
func (m *GetAnimeInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetAnimeInfoResponse.Size(m)
}
func (m *GetAnimeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimeInfoResponse proto.InternalMessageInfo

type isGetAnimeInfoResponse_Result interface {
	isGetAnimeInfoResponse_Result()
}

type GetAnimeInfoResponse_Anime struct {
	Anime *ShikiAnime `protobuf:"bytes,1,opt,name=anime,proto3,oneof"`
}

type GetAnimeInfoResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetAnimeInfoResponse_Anime) isGetAnimeInfoResponse_Result() {}

func (*GetAnimeInfoResponse_Error) isGetAnimeInfoResponse_Result() {}

func (m *GetAnimeInfoResponse) GetResult() isGetAnimeInfoResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetAnimeInfoResponse) GetAnime() *ShikiAnime {
	if x, ok := m.GetResult().(*GetAnimeInfoResponse_Anime); ok {
		return x.Anime
	}
	return nil
}

func (m *GetAnimeInfoResponse) GetError() *Error {
	if x, ok := m.GetResult().(*GetAnimeInfoResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetAnimeInfoResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetAnimeInfoResponse_Anime)(nil),
		(*GetAnimeInfoResponse_Error)(nil),
	}
}

type ShikiAnime struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Russian              string          `protobuf:"bytes,3,opt,name=russian,proto3" json:"russian,omitempty"`
	English              string          `protobuf:"bytes,4,opt,name=english,proto3" json:"english,omitempty"`
	Description          string          `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	DescriptionHtml      string          `protobuf:"bytes,6,opt,name=description_html,json=descriptionHtml,proto3" json:"descriptionHtml,omitempty"`
	DescriptionSource    string          `protobuf:"bytes,7,opt,name=description_source,json=descriptionSource,proto3" json:"descriptionSource,omitempty"`
	Score                float32         `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
	Kind                 string          `protobuf:"bytes,9,opt,name=kind,proto3" json:"kind,omitempty"`
	Status               string          `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	Episodes             int32           `protobuf:"varint,11,opt,name=episodes,proto3" json:"episodes,omitempty"`
	Poster               *Poster         `protobuf:"bytes,12,opt,name=poster,proto3" json:"poster,omitempty"`
	PersonRoles          []*PersonRole   `protobuf:"bytes,13,rep,name=person_roles,json=personRoles,proto3" json:"personRoles,omitempty"`
	ExternalLinks        []*ExternalLink `protobuf:"bytes,14,rep,name=external_links,json=externalLinks,proto3" json:"externalLinks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ShikiAnime) Reset()         { *m = ShikiAnime{} }
func (m *ShikiAnime) String() string { return proto.CompactTextString(m) }
func (*ShikiAnime) ProtoMessage()    {}
func (*ShikiAnime) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4d8bf40730cdee, []int{2}
}

func (m *ShikiAnime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShikiAnime.Unmarshal(m, b)
}
func (m *ShikiAnime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShikiAnime.Marshal(b, m, deterministic)
}
func (m *ShikiAnime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShikiAnime.Merge(m, src)
}
func (m *ShikiAnime) XXX_Size() int {
	return xxx_messageInfo_ShikiAnime.Size(m)
}
func (m *ShikiAnime) XXX_DiscardUnknown() {
	xxx_messageInfo_ShikiAnime.DiscardUnknown(m)
}

var xxx_messageInfo_ShikiAnime proto.InternalMessageInfo

func (m *ShikiAnime) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ShikiAnime) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShikiAnime) GetRussian() string {
	if m != nil {
		return m.Russian
	}
	return ""
}

func (m *ShikiAnime) GetEnglish() string {
	if m != nil {
		return m.English
	}
	return ""
}

func (m *ShikiAnime) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ShikiAnime) GetDescriptionHtml() string {
	if m != nil {
		return m.DescriptionHtml
	}
	return ""
}

func (m *ShikiAnime) GetDescriptionSource() string {
	if m != nil {
		return m.DescriptionSource
	}
	return ""
}

func (m *ShikiAnime) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ShikiAnime) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ShikiAnime) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ShikiAnime) GetEpisodes() int32 {
	if m != nil {
		return m.Episodes
	}
	return 0
}

func (m *ShikiAnime) GetPoster() *Poster {
	if m != nil {
		return m.Poster
	}
	return nil
}

func (m *ShikiAnime) GetPersonRoles() []*PersonRole {
	if m != nil {
		return m.PersonRoles
	}
	return nil
}

func (m *ShikiAnime) GetExternalLinks() []*ExternalLink {
	if m != nil {
		return m.ExternalLinks
	}
	return nil
}

type Poster struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalUrl          string   `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"originalUrl,omitempty"`
	MainUrl              string   `protobuf:"bytes,3,opt,name=main_url,json=mainUrl,proto3" json:"mainUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Poster) Reset()         { *m = Poster{} }
func (m *Poster) String() string { return proto.CompactTextString(m) }
func (*Poster) ProtoMessage()    {}
func (*Poster) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4d8bf40730cdee, []int{3}
}

func (m *Poster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Poster.Unmarshal(m, b)
}
func (m *Poster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Poster.Marshal(b, m, deterministic)
}
func (m *Poster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Poster.Merge(m, src)
}
func (m *Poster) XXX_Size() int {
	return xxx_messageInfo_Poster.Size(m)
}
func (m *Poster) XXX_DiscardUnknown() {
	xxx_messageInfo_Poster.DiscardUnknown(m)
}

var xxx_messageInfo_Poster proto.InternalMessageInfo

func (m *Poster) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Poster) GetOriginalUrl() string {
	if m != nil {
		return m.OriginalUrl
	}
	return ""
}

func (m *Poster) GetMainUrl() string {
	if m != nil {
		return m.MainUrl
	}
	return ""
}

type PersonRole struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RolesRu              []string `protobuf:"bytes,2,rep,name=roles_ru,json=rolesRu,proto3" json:"rolesRu,omitempty"`
	RolesEn              []string `protobuf:"bytes,3,rep,name=roles_en,json=rolesEn,proto3" json:"rolesEn,omitempty"`
	Person               *Person  `protobuf:"bytes,4,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonRole) Reset()         { *m = PersonRole{} }
func (m *PersonRole) String() string { return proto.CompactTextString(m) }
func (*PersonRole) ProtoMessage()    {}
func (*PersonRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4d8bf40730cdee, []int{4}
}

func (m *PersonRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonRole.Unmarshal(m, b)
}
func (m *PersonRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonRole.Marshal(b, m, deterministic)
}
func (m *PersonRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonRole.Merge(m, src)
}
func (m *PersonRole) XXX_Size() int {
	return xxx_messageInfo_PersonRole.Size(m)
}
func (m *PersonRole) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonRole.DiscardUnknown(m)
}

var xxx_messageInfo_PersonRole proto.InternalMessageInfo

func (m *PersonRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PersonRole) GetRolesRu() []string {
	if m != nil {
		return m.RolesRu
	}
	return nil
}

func (m *PersonRole) GetRolesEn() []string {
	if m != nil {
		return m.RolesEn
	}
	return nil
}

func (m *PersonRole) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type Person struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Poster               *Poster  `protobuf:"bytes,3,opt,name=poster,proto3" json:"poster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4d8bf40730cdee, []int{5}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetPoster() *Poster {
	if m != nil {
		return m.Poster
	}
	return nil
}

type ExternalLink struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind                 string   `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExternalLink) Reset()         { *m = ExternalLink{} }
func (m *ExternalLink) String() string { return proto.CompactTextString(m) }
func (*ExternalLink) ProtoMessage()    {}
func (*ExternalLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4d8bf40730cdee, []int{6}
}

func (m *ExternalLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalLink.Unmarshal(m, b)
}
func (m *ExternalLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalLink.Marshal(b, m, deterministic)
}
func (m *ExternalLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalLink.Merge(m, src)
}
func (m *ExternalLink) XXX_Size() int {
	return xxx_messageInfo_ExternalLink.Size(m)
}
func (m *ExternalLink) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalLink.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalLink proto.InternalMessageInfo

func (m *ExternalLink) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ExternalLink) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *ExternalLink) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f4d8bf40730cdee, []int{7}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAnimeInfoRequest)(nil), "shikimori.GetAnimeInfoRequest")
	proto.RegisterType((*GetAnimeInfoResponse)(nil), "shikimori.GetAnimeInfoResponse")
	proto.RegisterType((*ShikiAnime)(nil), "shikimori.ShikiAnime")
	proto.RegisterType((*Poster)(nil), "shikimori.Poster")
	proto.RegisterType((*PersonRole)(nil), "shikimori.PersonRole")
	proto.RegisterType((*Person)(nil), "shikimori.Person")
	proto.RegisterType((*ExternalLink)(nil), "shikimori.ExternalLink")
	proto.RegisterType((*Error)(nil), "shikimori.Error")
}

func init() {
	proto.RegisterFile("internal/shared/proto/shikimori.proto", fileDescriptor_7f4d8bf40730cdee)
}

var fileDescriptor_7f4d8bf40730cdee = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xfd, 0x92, 0x34, 0x6e, 0x32, 0x49, 0xfb, 0xa5, 0x4b, 0x81, 0x6d, 0x0f, 0xe0, 0x5a, 0x42,
	0x4a, 0x0f, 0x6d, 0xa4, 0x72, 0xe1, 0x84, 0x44, 0x45, 0x45, 0x91, 0x90, 0xa8, 0x1c, 0x15, 0x24,
	0x2e, 0x91, 0x49, 0x86, 0x66, 0x15, 0x7b, 0xd7, 0xec, 0xd8, 0x08, 0x0e, 0xfc, 0x5a, 0xfe, 0x08,
	0xda, 0xb1, 0x53, 0x2f, 0x6d, 0x51, 0xb9, 0xcd, 0x9b, 0xf7, 0x3c, 0x9e, 0x9d, 0x37, 0xbb, 0xf0,
	0x4c, 0xe9, 0x02, 0xad, 0x4e, 0xd2, 0x09, 0x2d, 0x13, 0x8b, 0x8b, 0x49, 0x6e, 0x4d, 0x61, 0x26,
	0xb4, 0x54, 0x2b, 0x95, 0x19, 0xab, 0x8e, 0x19, 0x8b, 0xfe, 0x75, 0x22, 0x3a, 0x82, 0x07, 0x6f,
	0xb0, 0x78, 0xa5, 0x55, 0x86, 0x6f, 0xf5, 0x17, 0x13, 0xe3, 0xd7, 0x12, 0xa9, 0x10, 0x8f, 0x20,
	0x20, 0x4c, 0xec, 0x7c, 0x29, 0x5b, 0x61, 0x6b, 0xdc, 0x8f, 0x6b, 0x14, 0xfd, 0x80, 0xdd, 0x3f,
	0xe5, 0x94, 0x1b, 0x4d, 0x28, 0x8e, 0xa0, 0x9b, 0xb8, 0x24, 0xcb, 0x07, 0x27, 0x0f, 0x8f, 0x9b,
	0x5f, 0x4e, 0x5d, 0xc4, 0x5f, 0x9c, 0xff, 0x17, 0x57, 0x2a, 0x31, 0x86, 0x2e, 0x5a, 0x6b, 0xac,
	0x6c, 0xb3, 0x7c, 0xe4, 0xc9, 0xcf, 0x5c, 0xde, 0x29, 0x59, 0x70, 0xda, 0x83, 0xc0, 0x22, 0x95,
	0x69, 0x11, 0xfd, 0xea, 0x00, 0x34, 0xb5, 0xc4, 0x36, 0xb4, 0xd5, 0xa2, 0xee, 0xae, 0xad, 0x16,
	0x42, 0xc0, 0x86, 0x4e, 0x32, 0xe4, 0x8a, 0xfd, 0x98, 0x63, 0x21, 0x61, 0xd3, 0x96, 0x44, 0x2a,
	0xd1, 0xb2, 0xc3, 0xe9, 0x35, 0x74, 0x0c, 0xea, 0xab, 0x54, 0xd1, 0x52, 0x6e, 0x54, 0x4c, 0x0d,
	0x45, 0x08, 0x83, 0x05, 0xd2, 0xdc, 0xaa, 0xbc, 0x50, 0x46, 0xcb, 0x2e, 0xb3, 0x7e, 0x4a, 0x1c,
	0xc2, 0xc8, 0x83, 0xb3, 0x65, 0x91, 0xa5, 0x32, 0x60, 0xd9, 0xff, 0x5e, 0xfe, 0xbc, 0xc8, 0x52,
	0x71, 0x04, 0xc2, 0x97, 0x92, 0x29, 0xed, 0x1c, 0xe5, 0x26, 0x8b, 0x77, 0x3c, 0x66, 0xca, 0x84,
	0xd8, 0x85, 0x2e, 0xcd, 0x8d, 0x45, 0xd9, 0x0b, 0x5b, 0xe3, 0x76, 0x5c, 0x01, 0x77, 0xb2, 0x95,
	0xd2, 0x0b, 0xd9, 0xaf, 0x4e, 0xe6, 0x62, 0xf6, 0xa7, 0x48, 0x8a, 0x92, 0x24, 0xd4, 0xfe, 0x30,
	0x12, 0xfb, 0xd0, 0xc3, 0x5c, 0x91, 0x59, 0x20, 0xc9, 0x41, 0xd8, 0x1a, 0x77, 0xe3, 0x6b, 0x2c,
	0x0e, 0x21, 0xc8, 0x0d, 0x15, 0x68, 0xe5, 0x90, 0xa7, 0xbe, 0xe3, 0x4d, 0xfd, 0x82, 0x89, 0xb8,
	0x16, 0x88, 0x17, 0x30, 0xcc, 0xd1, 0x92, 0xd1, 0x33, 0x6b, 0x52, 0x24, 0xb9, 0x15, 0x76, 0x6e,
	0xb8, 0x7a, 0xc1, 0x74, 0x6c, 0x52, 0x8c, 0x07, 0xf9, 0x75, 0x4c, 0xe2, 0x25, 0x6c, 0xe3, 0xf7,
	0x6a, 0x07, 0x67, 0xa9, 0xd2, 0x2b, 0x92, 0xdb, 0xfc, 0xed, 0x63, 0xdf, 0xe2, 0x5a, 0xf0, 0x4e,
	0xe9, 0x55, 0xbc, 0x85, 0x1e, 0xa2, 0xe8, 0x03, 0x04, 0x55, 0x2f, 0xb7, 0x0c, 0x3e, 0x80, 0xa1,
	0xb1, 0xea, 0x4a, 0xb9, 0xca, 0xa5, 0x4d, 0x6b, 0xa3, 0x07, 0xeb, 0xdc, 0xa5, 0x4d, 0xc5, 0x1e,
	0xf4, 0xb2, 0x44, 0x69, 0xa6, 0x6b, 0xc3, 0x1d, 0xbe, 0xb4, 0x69, 0xf4, 0x13, 0xa0, 0x69, 0xf9,
	0x56, 0xed, 0x3d, 0xe8, 0xf1, 0x41, 0x67, 0xb6, 0x94, 0xed, 0xb0, 0xc3, 0x9b, 0xe2, 0x70, 0x5c,
	0x36, 0x14, 0xba, 0x25, 0x6a, 0xa8, 0x33, 0xcd, 0x03, 0xe5, 0x9a, 0xbc, 0x43, 0x37, 0x06, 0x5a,
	0xfd, 0xac, 0x16, 0x44, 0x1f, 0x21, 0xa8, 0x32, 0xff, 0xb4, 0xb7, 0x8d, 0x53, 0x9d, 0x7b, 0x9c,
	0x8a, 0x5e, 0xc3, 0xd0, 0x1f, 0xe7, 0x5d, 0xe5, 0x79, 0x79, 0xda, 0xde, 0xf2, 0x8c, 0xa0, 0xd3,
	0x4c, 0xc8, 0x85, 0xd1, 0x01, 0x74, 0xf9, 0xde, 0xb9, 0x7b, 0x91, 0x21, 0x51, 0x72, 0x85, 0x75,
	0x8d, 0x35, 0x3c, 0x99, 0xc3, 0x68, 0xba, 0x6e, 0x62, 0x8a, 0xf6, 0x9b, 0x9a, 0xa3, 0x78, 0x0f,
	0x43, 0xff, 0x35, 0x10, 0x4f, 0xbc, 0x3e, 0xef, 0x78, 0x55, 0xf6, 0x9f, 0xfe, 0x95, 0xaf, 0x9e,
	0x91, 0xd3, 0xe8, 0x53, 0x38, 0xb9, 0xe7, 0x09, 0xfb, 0x1c, 0x70, 0xe2, 0xf9, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x92, 0x51, 0x12, 0x61, 0xec, 0x04, 0x00, 0x00,
}
