// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: anidb.proto

package anidb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AniDBService_GetAniDBId_FullMethodName = "/anidb.AniDBService/GetAniDBId"
)

// AniDBServiceClient is the client API for AniDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AniDBServiceClient interface {
	GetAniDBId(ctx context.Context, in *GetAniDBIdRequest, opts ...grpc.CallOption) (*GetAniDBIdResponse, error)
}

type aniDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAniDBServiceClient(cc grpc.ClientConnInterface) AniDBServiceClient {
	return &aniDBServiceClient{cc}
}

func (c *aniDBServiceClient) GetAniDBId(ctx context.Context, in *GetAniDBIdRequest, opts ...grpc.CallOption) (*GetAniDBIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAniDBIdResponse)
	err := c.cc.Invoke(ctx, AniDBService_GetAniDBId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AniDBServiceServer is the server API for AniDBService service.
// All implementations must embed UnimplementedAniDBServiceServer
// for forward compatibility.
type AniDBServiceServer interface {
	GetAniDBId(context.Context, *GetAniDBIdRequest) (*GetAniDBIdResponse, error)
	mustEmbedUnimplementedAniDBServiceServer()
}

// UnimplementedAniDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAniDBServiceServer struct{}

func (UnimplementedAniDBServiceServer) GetAniDBId(context.Context, *GetAniDBIdRequest) (*GetAniDBIdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAniDBId not implemented")
}
func (UnimplementedAniDBServiceServer) mustEmbedUnimplementedAniDBServiceServer() {}
func (UnimplementedAniDBServiceServer) testEmbeddedByValue()                      {}

// UnsafeAniDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AniDBServiceServer will
// result in compilation errors.
type UnsafeAniDBServiceServer interface {
	mustEmbedUnimplementedAniDBServiceServer()
}

func RegisterAniDBServiceServer(s grpc.ServiceRegistrar, srv AniDBServiceServer) {
	// If the following call panics, it indicates UnimplementedAniDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AniDBService_ServiceDesc, srv)
}

func _AniDBService_GetAniDBId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAniDBIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AniDBServiceServer).GetAniDBId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AniDBService_GetAniDBId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AniDBServiceServer).GetAniDBId(ctx, req.(*GetAniDBIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AniDBService_ServiceDesc is the grpc.ServiceDesc for AniDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AniDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anidb.AniDBService",
	HandlerType: (*AniDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAniDBId",
			Handler:    _AniDBService_GetAniDBId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anidb.proto",
}
