// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/shared/proto/anidb.proto

package anidb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAniDBIdRequest struct {
	AnimeName            string   `protobuf:"bytes,1,opt,name=anime_name,json=animeName,proto3" json:"anime_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAniDBIdRequest) Reset()         { *m = GetAniDBIdRequest{} }
func (m *GetAniDBIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetAniDBIdRequest) ProtoMessage()    {}
func (*GetAniDBIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_356c269050e4400d, []int{0}
}

func (m *GetAniDBIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAniDBIdRequest.Unmarshal(m, b)
}
func (m *GetAniDBIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAniDBIdRequest.Marshal(b, m, deterministic)
}
func (m *GetAniDBIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAniDBIdRequest.Merge(m, src)
}
func (m *GetAniDBIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetAniDBIdRequest.Size(m)
}
func (m *GetAniDBIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAniDBIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAniDBIdRequest proto.InternalMessageInfo

func (m *GetAniDBIdRequest) GetAnimeName() string {
	if m != nil {
		return m.AnimeName
	}
	return ""
}

type GetAniDBIdResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAniDBIdResponse) Reset()         { *m = GetAniDBIdResponse{} }
func (m *GetAniDBIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetAniDBIdResponse) ProtoMessage()    {}
func (*GetAniDBIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_356c269050e4400d, []int{1}
}

func (m *GetAniDBIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAniDBIdResponse.Unmarshal(m, b)
}
func (m *GetAniDBIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAniDBIdResponse.Marshal(b, m, deterministic)
}
func (m *GetAniDBIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAniDBIdResponse.Merge(m, src)
}
func (m *GetAniDBIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetAniDBIdResponse.Size(m)
}
func (m *GetAniDBIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAniDBIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAniDBIdResponse proto.InternalMessageInfo

func (m *GetAniDBIdResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetAniDBIdResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AnimeTitle struct {
	AnimeId              int32    `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Lang                 string   `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeTitle) Reset()         { *m = AnimeTitle{} }
func (m *AnimeTitle) String() string { return proto.CompactTextString(m) }
func (*AnimeTitle) ProtoMessage()    {}
func (*AnimeTitle) Descriptor() ([]byte, []int) {
	return fileDescriptor_356c269050e4400d, []int{2}
}

func (m *AnimeTitle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeTitle.Unmarshal(m, b)
}
func (m *AnimeTitle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeTitle.Marshal(b, m, deterministic)
}
func (m *AnimeTitle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeTitle.Merge(m, src)
}
func (m *AnimeTitle) XXX_Size() int {
	return xxx_messageInfo_AnimeTitle.Size(m)
}
func (m *AnimeTitle) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeTitle.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeTitle proto.InternalMessageInfo

func (m *AnimeTitle) GetAnimeId() int32 {
	if m != nil {
		return m.AnimeId
	}
	return 0
}

func (m *AnimeTitle) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *AnimeTitle) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *AnimeTitle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type AnimeTitles struct {
	Titles               []*AnimeTitle `protobuf:"bytes,1,rep,name=titles,proto3" json:"titles,omitempty"`
	Error                string        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *AnimeTitles) Reset()         { *m = AnimeTitles{} }
func (m *AnimeTitles) String() string { return proto.CompactTextString(m) }
func (*AnimeTitles) ProtoMessage()    {}
func (*AnimeTitles) Descriptor() ([]byte, []int) {
	return fileDescriptor_356c269050e4400d, []int{3}
}

func (m *AnimeTitles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeTitles.Unmarshal(m, b)
}
func (m *AnimeTitles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeTitles.Marshal(b, m, deterministic)
}
func (m *AnimeTitles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeTitles.Merge(m, src)
}
func (m *AnimeTitles) XXX_Size() int {
	return xxx_messageInfo_AnimeTitles.Size(m)
}
func (m *AnimeTitles) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeTitles.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeTitles proto.InternalMessageInfo

func (m *AnimeTitles) GetTitles() []*AnimeTitle {
	if m != nil {
		return m.Titles
	}
	return nil
}

func (m *AnimeTitles) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type AnimeIdRequest struct {
	AnimeId              int32    `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeIdRequest) Reset()         { *m = AnimeIdRequest{} }
func (m *AnimeIdRequest) String() string { return proto.CompactTextString(m) }
func (*AnimeIdRequest) ProtoMessage()    {}
func (*AnimeIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_356c269050e4400d, []int{4}
}

func (m *AnimeIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeIdRequest.Unmarshal(m, b)
}
func (m *AnimeIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeIdRequest.Marshal(b, m, deterministic)
}
func (m *AnimeIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeIdRequest.Merge(m, src)
}
func (m *AnimeIdRequest) XXX_Size() int {
	return xxx_messageInfo_AnimeIdRequest.Size(m)
}
func (m *AnimeIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeIdRequest proto.InternalMessageInfo

func (m *AnimeIdRequest) GetAnimeId() int32 {
	if m != nil {
		return m.AnimeId
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAniDBIdRequest)(nil), "anidb.GetAniDBIdRequest")
	proto.RegisterType((*GetAniDBIdResponse)(nil), "anidb.GetAniDBIdResponse")
	proto.RegisterType((*AnimeTitle)(nil), "anidb.AnimeTitle")
	proto.RegisterType((*AnimeTitles)(nil), "anidb.AnimeTitles")
	proto.RegisterType((*AnimeIdRequest)(nil), "anidb.AnimeIdRequest")
}

func init() {
	proto.RegisterFile("internal/shared/proto/anidb.proto", fileDescriptor_356c269050e4400d)
}

var fileDescriptor_356c269050e4400d = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x6b, 0xc2, 0x40,
	0x10, 0x25, 0x7e, 0xb5, 0x8e, 0xad, 0xe0, 0xd0, 0x42, 0x2c, 0x14, 0x6c, 0x28, 0xc5, 0x52, 0x30,
	0x60, 0x6f, 0xde, 0x22, 0x05, 0xf1, 0x62, 0x21, 0xf6, 0xd4, 0x8b, 0xac, 0x66, 0xd0, 0x85, 0x64,
	0x37, 0xdd, 0x5d, 0x0b, 0xfd, 0x99, 0xfd, 0x47, 0x25, 0xbb, 0x69, 0x15, 0xac, 0xde, 0xe6, 0x4d,
	0xde, 0x9b, 0x37, 0xf3, 0xb2, 0x70, 0xc7, 0x85, 0x21, 0x25, 0x58, 0x1a, 0xea, 0x0d, 0x53, 0x94,
	0x84, 0xb9, 0x92, 0x46, 0x86, 0x4c, 0xf0, 0x64, 0x39, 0xb0, 0x35, 0xd6, 0x2d, 0x08, 0x86, 0xd0,
	0x99, 0x90, 0x89, 0x04, 0x7f, 0x19, 0x4f, 0x93, 0x98, 0x3e, 0xb6, 0xa4, 0x0d, 0xde, 0x02, 0x30,
	0xc1, 0x33, 0x5a, 0x08, 0x96, 0x91, 0xef, 0xf5, 0xbc, 0x7e, 0x33, 0x6e, 0xda, 0xce, 0x8c, 0x65,
	0x14, 0x8c, 0x00, 0xf7, 0x35, 0x3a, 0x97, 0x42, 0x13, 0xb6, 0xa1, 0xc2, 0x13, 0x4b, 0xae, 0xc7,
	0x15, 0x9e, 0xe0, 0x15, 0xd4, 0x49, 0x29, 0xa9, 0xfc, 0x8a, 0xd5, 0x3b, 0x10, 0x10, 0x40, 0x54,
	0x0c, 0x7a, 0xe3, 0x26, 0x25, 0xec, 0xc2, 0xb9, 0x33, 0xfa, 0x53, 0x9e, 0x59, 0x3c, 0x4d, 0x10,
	0xa1, 0x66, 0xbe, 0x72, 0x2a, 0xd5, 0xb6, 0x2e, 0x7a, 0x29, 0x13, 0x6b, 0xbf, 0xea, 0x7a, 0x45,
	0x5d, 0xd8, 0x98, 0x62, 0x96, 0x5f, 0x73, 0x36, 0x16, 0x04, 0x33, 0x68, 0xed, 0x6c, 0x34, 0x3e,
	0x42, 0xc3, 0xf6, 0xb5, 0xef, 0xf5, 0xaa, 0xfd, 0xd6, 0xb0, 0x33, 0x70, 0x51, 0xec, 0x38, 0x71,
	0x49, 0x38, 0xb2, 0xf6, 0x13, 0xb4, 0x23, 0xb7, 0xd8, 0x6f, 0x46, 0xc7, 0x57, 0x1f, 0x7e, 0x7b,
	0x70, 0x61, 0xd3, 0x99, 0x93, 0xfa, 0xe4, 0x2b, 0xc2, 0x08, 0x60, 0x17, 0x18, 0xfa, 0xa5, 0xf9,
	0x41, 0xee, 0x37, 0xdd, 0x7f, 0xbe, 0x94, 0xe9, 0x8e, 0x01, 0xa3, 0xad, 0x91, 0x2b, 0x99, 0xe5,
	0x29, 0x19, 0x9a, 0x13, 0x53, 0xab, 0xcd, 0x89, 0x51, 0x78, 0x70, 0xa1, 0xc6, 0x11, 0x5c, 0x4e,
	0xc8, 0xbc, 0x9a, 0x0d, 0xa9, 0xe2, 0x3f, 0x6a, 0xbc, 0xde, 0x27, 0x9d, 0xd4, 0x8e, 0x1f, 0xde,
	0xef, 0xd7, 0x72, 0x61, 0x2f, 0x0c, 0x4f, 0x3c, 0xae, 0x65, 0xc3, 0x82, 0xe7, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x9b, 0x1a, 0xdf, 0x86, 0x82, 0x02, 0x00, 0x00,
}
