// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anidb.proto

package anidb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAniDBIdRequest struct {
	AnimeName            string   `protobuf:"bytes,1,opt,name=anime_name,json=animeName,proto3" json:"anime_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAniDBIdRequest) Reset()         { *m = GetAniDBIdRequest{} }
func (m *GetAniDBIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetAniDBIdRequest) ProtoMessage()    {}
func (*GetAniDBIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7cd92dc93f90b8e, []int{0}
}

func (m *GetAniDBIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAniDBIdRequest.Unmarshal(m, b)
}
func (m *GetAniDBIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAniDBIdRequest.Marshal(b, m, deterministic)
}
func (m *GetAniDBIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAniDBIdRequest.Merge(m, src)
}
func (m *GetAniDBIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetAniDBIdRequest.Size(m)
}
func (m *GetAniDBIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAniDBIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAniDBIdRequest proto.InternalMessageInfo

func (m *GetAniDBIdRequest) GetAnimeName() string {
	if m != nil {
		return m.AnimeName
	}
	return ""
}

type GetAniDBIdResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAniDBIdResponse) Reset()         { *m = GetAniDBIdResponse{} }
func (m *GetAniDBIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetAniDBIdResponse) ProtoMessage()    {}
func (*GetAniDBIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c7cd92dc93f90b8e, []int{1}
}

func (m *GetAniDBIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAniDBIdResponse.Unmarshal(m, b)
}
func (m *GetAniDBIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAniDBIdResponse.Marshal(b, m, deterministic)
}
func (m *GetAniDBIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAniDBIdResponse.Merge(m, src)
}
func (m *GetAniDBIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetAniDBIdResponse.Size(m)
}
func (m *GetAniDBIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAniDBIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAniDBIdResponse proto.InternalMessageInfo

func (m *GetAniDBIdResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetAniDBIdResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAniDBIdRequest)(nil), "anidb.GetAniDBIdRequest")
	proto.RegisterType((*GetAniDBIdResponse)(nil), "anidb.GetAniDBIdResponse")
}

func init() { proto.RegisterFile("anidb.proto", fileDescriptor_c7cd92dc93f90b8e) }

var fileDescriptor_c7cd92dc93f90b8e = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xb1, 0xab, 0xc2, 0x30,
	0x10, 0x87, 0x69, 0xa1, 0x0f, 0x7a, 0xef, 0xf1, 0xc0, 0xe0, 0x50, 0x05, 0x41, 0x8a, 0x88, 0x53,
	0x03, 0x75, 0x73, 0x6b, 0x11, 0xc4, 0x45, 0xb0, 0x6e, 0x2e, 0x25, 0x35, 0x87, 0x06, 0x6c, 0x52,
	0x93, 0xe8, 0xdf, 0x2f, 0x5c, 0x07, 0x05, 0x1d, 0x7f, 0x77, 0xf7, 0xdd, 0x7d, 0x07, 0xbf, 0x42,
	0x2b, 0xd9, 0x64, 0x9d, 0x35, 0xde, 0xb0, 0x88, 0x42, 0x9a, 0xc3, 0x60, 0x83, 0xbe, 0xd0, 0x6a,
	0x5d, 0x6e, 0x65, 0x85, 0xb7, 0x3b, 0x3a, 0xcf, 0x26, 0x00, 0x42, 0xab, 0x16, 0x6b, 0x2d, 0x5a,
	0x4c, 0x82, 0x69, 0xb0, 0x88, 0xab, 0x98, 0x2a, 0x3b, 0xd1, 0x62, 0xba, 0x02, 0xf6, 0xce, 0xb8,
	0xce, 0x68, 0x87, 0xec, 0x1f, 0x42, 0x25, 0x69, 0x38, 0xaa, 0x42, 0x25, 0xd9, 0x10, 0x22, 0xb4,
	0xd6, 0xd8, 0x24, 0x24, 0xbe, 0x0f, 0xf9, 0x1e, 0xfe, 0x08, 0x3c, 0xa0, 0x7d, 0xa8, 0x13, 0xb2,
	0x02, 0xe0, 0xb5, 0x8b, 0x25, 0x59, 0xaf, 0xf8, 0xa1, 0x34, 0x1e, 0x7d, 0xe9, 0xf4, 0x87, 0xcb,
	0xf9, 0x71, 0x76, 0x36, 0x35, 0xe9, 0x71, 0xa5, 0x3d, 0x5a, 0x2d, 0xae, 0xdc, 0x5d, 0x84, 0x45,
	0xc9, 0xe9, 0x57, 0x4e, 0x68, 0xf3, 0x43, 0x61, 0xf9, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x56, 0x19,
	0xa4, 0xfe, 0x07, 0x01, 0x00, 0x00,
}
