// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/shared/proto/animetosho.proto

package animetosho

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Запрос
type GetParsedEpisodesRequest struct {
	AnidbId              uint32   `protobuf:"varint,1,opt,name=anidb_id,json=anidbId,proto3" json:"anidb_id,omitempty"`
	AnimeId              uint32   `protobuf:"varint,2,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParsedEpisodesRequest) Reset()         { *m = GetParsedEpisodesRequest{} }
func (m *GetParsedEpisodesRequest) String() string { return proto.CompactTextString(m) }
func (*GetParsedEpisodesRequest) ProtoMessage()    {}
func (*GetParsedEpisodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_194153eb0a075e47, []int{0}
}

func (m *GetParsedEpisodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParsedEpisodesRequest.Unmarshal(m, b)
}
func (m *GetParsedEpisodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParsedEpisodesRequest.Marshal(b, m, deterministic)
}
func (m *GetParsedEpisodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParsedEpisodesRequest.Merge(m, src)
}
func (m *GetParsedEpisodesRequest) XXX_Size() int {
	return xxx_messageInfo_GetParsedEpisodesRequest.Size(m)
}
func (m *GetParsedEpisodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParsedEpisodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetParsedEpisodesRequest proto.InternalMessageInfo

func (m *GetParsedEpisodesRequest) GetAnidbId() uint32 {
	if m != nil {
		return m.AnidbId
	}
	return 0
}

func (m *GetParsedEpisodesRequest) GetAnimeId() uint32 {
	if m != nil {
		return m.AnimeId
	}
	return 0
}

// Ответ
type GetParsedEpisodesResponse struct {
	Episodes             []*AnimeEpisode `protobuf:"bytes,1,rep,name=episodes,proto3" json:"episodes,omitempty"`
	ErrorMessage         string          `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	HasEpisodes          bool            `protobuf:"varint,3,opt,name=has_episodes,json=hasEpisodes,proto3" json:"has_episodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetParsedEpisodesResponse) Reset()         { *m = GetParsedEpisodesResponse{} }
func (m *GetParsedEpisodesResponse) String() string { return proto.CompactTextString(m) }
func (*GetParsedEpisodesResponse) ProtoMessage()    {}
func (*GetParsedEpisodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_194153eb0a075e47, []int{1}
}

func (m *GetParsedEpisodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParsedEpisodesResponse.Unmarshal(m, b)
}
func (m *GetParsedEpisodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParsedEpisodesResponse.Marshal(b, m, deterministic)
}
func (m *GetParsedEpisodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParsedEpisodesResponse.Merge(m, src)
}
func (m *GetParsedEpisodesResponse) XXX_Size() int {
	return xxx_messageInfo_GetParsedEpisodesResponse.Size(m)
}
func (m *GetParsedEpisodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParsedEpisodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetParsedEpisodesResponse proto.InternalMessageInfo

func (m *GetParsedEpisodesResponse) GetEpisodes() []*AnimeEpisode {
	if m != nil {
		return m.Episodes
	}
	return nil
}

func (m *GetParsedEpisodesResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *GetParsedEpisodesResponse) GetHasEpisodes() bool {
	if m != nil {
		return m.HasEpisodes
	}
	return false
}

// Структура, максимально близкая к вашей AnimeEpisodeModel
type AnimeEpisode struct {
	AnimeId              uint32   `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	EpisodeNumber        int32    `protobuf:"varint,2,opt,name=episode_number,json=episodeNumber,proto3" json:"episode_number,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Translator           string   `protobuf:"bytes,4,opt,name=translator,proto3" json:"translator,omitempty"`
	Width                string   `protobuf:"bytes,5,opt,name=width,proto3" json:"width,omitempty"`
	TorrentUrl           string   `protobuf:"bytes,6,opt,name=torrent_url,json=torrentUrl,proto3" json:"torrent_url,omitempty"`
	MagnetUrl            string   `protobuf:"bytes,7,opt,name=magnet_url,json=magnetUrl,proto3" json:"magnet_url,omitempty"`
	LocalUrl             string   `protobuf:"bytes,8,opt,name=local_url,json=localUrl,proto3" json:"local_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeEpisode) Reset()         { *m = AnimeEpisode{} }
func (m *AnimeEpisode) String() string { return proto.CompactTextString(m) }
func (*AnimeEpisode) ProtoMessage()    {}
func (*AnimeEpisode) Descriptor() ([]byte, []int) {
	return fileDescriptor_194153eb0a075e47, []int{2}
}

func (m *AnimeEpisode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeEpisode.Unmarshal(m, b)
}
func (m *AnimeEpisode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeEpisode.Marshal(b, m, deterministic)
}
func (m *AnimeEpisode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeEpisode.Merge(m, src)
}
func (m *AnimeEpisode) XXX_Size() int {
	return xxx_messageInfo_AnimeEpisode.Size(m)
}
func (m *AnimeEpisode) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeEpisode.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeEpisode proto.InternalMessageInfo

func (m *AnimeEpisode) GetAnimeId() uint32 {
	if m != nil {
		return m.AnimeId
	}
	return 0
}

func (m *AnimeEpisode) GetEpisodeNumber() int32 {
	if m != nil {
		return m.EpisodeNumber
	}
	return 0
}

func (m *AnimeEpisode) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnimeEpisode) GetTranslator() string {
	if m != nil {
		return m.Translator
	}
	return ""
}

func (m *AnimeEpisode) GetWidth() string {
	if m != nil {
		return m.Width
	}
	return ""
}

func (m *AnimeEpisode) GetTorrentUrl() string {
	if m != nil {
		return m.TorrentUrl
	}
	return ""
}

func (m *AnimeEpisode) GetMagnetUrl() string {
	if m != nil {
		return m.MagnetUrl
	}
	return ""
}

func (m *AnimeEpisode) GetLocalUrl() string {
	if m != nil {
		return m.LocalUrl
	}
	return ""
}

func init() {
	proto.RegisterType((*GetParsedEpisodesRequest)(nil), "animetosho.GetParsedEpisodesRequest")
	proto.RegisterType((*GetParsedEpisodesResponse)(nil), "animetosho.GetParsedEpisodesResponse")
	proto.RegisterType((*AnimeEpisode)(nil), "animetosho.AnimeEpisode")
}

func init() {
	proto.RegisterFile("internal/shared/proto/animetosho.proto", fileDescriptor_194153eb0a075e47)
}

var fileDescriptor_194153eb0a075e47 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0xee, 0xd3, 0x30,
	0x0c, 0x80, 0x55, 0xf6, 0xaf, 0xf5, 0x36, 0xa4, 0x45, 0x1c, 0x3a, 0x10, 0x50, 0x0a, 0x43, 0x3b,
	0x6d, 0xd2, 0xe0, 0x05, 0x40, 0x42, 0x68, 0x07, 0xd0, 0x54, 0xd8, 0x85, 0x4b, 0xc9, 0x16, 0x6b,
	0xad, 0xd4, 0x26, 0xc3, 0x49, 0xe1, 0x59, 0x78, 0x52, 0xae, 0xa8, 0x6e, 0x19, 0x9d, 0xe0, 0xa7,
	0xdd, 0x92, 0xef, 0x4b, 0xec, 0x38, 0x36, 0xbc, 0xcc, 0xb5, 0x43, 0xd2, 0xb2, 0x58, 0xdb, 0x4c,
	0x12, 0xaa, 0xf5, 0x99, 0x8c, 0x33, 0x6b, 0xa9, 0xf3, 0x12, 0x9d, 0xb1, 0x99, 0x59, 0x31, 0x10,
	0xf0, 0x97, 0xc4, 0x3b, 0x08, 0xdf, 0xa3, 0xdb, 0x49, 0xb2, 0xa8, 0xde, 0x9d, 0x73, 0x6b, 0x14,
	0xda, 0x04, 0xbf, 0x55, 0x68, 0x9d, 0x98, 0x83, 0x2f, 0x75, 0xae, 0x0e, 0x69, 0xae, 0x42, 0x2f,
	0xf2, 0x96, 0xd3, 0x64, 0xc4, 0xfb, 0xad, 0x6a, 0x55, 0x89, 0xb5, 0xba, 0x77, 0x51, 0x25, 0x6e,
	0x55, 0xfc, 0xd3, 0x83, 0xf9, 0x7f, 0x42, 0xda, 0xb3, 0xd1, 0x16, 0xc5, 0x6b, 0xf0, 0xb1, 0x65,
	0xa1, 0x17, 0xf5, 0x96, 0xe3, 0x4d, 0xb8, 0xea, 0x3c, 0xf0, 0x4d, 0xbd, 0x6c, 0x2f, 0x25, 0x97,
	0x93, 0xe2, 0x39, 0x4c, 0x91, 0xc8, 0x50, 0x5a, 0xa2, 0xb5, 0xf2, 0x84, 0x9c, 0x33, 0x48, 0x26,
	0x0c, 0x3f, 0x34, 0x4c, 0x3c, 0x83, 0x49, 0x26, 0x6d, 0x7a, 0x09, 0xdf, 0x8b, 0xbc, 0xa5, 0x9f,
	0x8c, 0x33, 0x69, 0xff, 0xbc, 0x22, 0xfe, 0xe5, 0xc1, 0xa4, 0x9b, 0xe2, 0xaa, 0x0e, 0xef, 0xaa,
	0x0e, 0xb1, 0x80, 0xfb, 0x6d, 0xa8, 0x54, 0x57, 0xe5, 0x01, 0x89, 0x93, 0x0e, 0x92, 0x69, 0x4b,
	0x3f, 0x32, 0x14, 0x02, 0xfa, 0x5a, 0x96, 0xc8, 0xd9, 0x82, 0x84, 0xd7, 0xe2, 0x09, 0x80, 0x23,
	0xa9, 0x6d, 0x21, 0x9d, 0xa1, 0xb0, 0xcf, 0xa6, 0x43, 0xc4, 0x03, 0x18, 0xfc, 0xc8, 0x95, 0xcb,
	0xc2, 0x01, 0xab, 0x66, 0x23, 0x9e, 0xc2, 0xd8, 0x19, 0x22, 0xd4, 0x2e, 0xad, 0xa8, 0x08, 0x87,
	0xed, 0xb5, 0x06, 0xed, 0xa9, 0x10, 0x8f, 0x01, 0x4a, 0x79, 0xd2, 0xd8, 0xf8, 0x11, 0xfb, 0xa0,
	0x21, 0xb5, 0x7e, 0x04, 0x41, 0x61, 0x8e, 0xb2, 0x60, 0xeb, 0xb3, 0xf5, 0x19, 0xec, 0xa9, 0xd8,
	0x54, 0x30, 0xe3, 0xc2, 0x3f, 0xd7, 0xdf, 0xfc, 0x09, 0xe9, 0x7b, 0x7e, 0x44, 0xf1, 0x15, 0x66,
	0xff, 0x74, 0x4a, 0xbc, 0xe8, 0xf6, 0xe3, 0xae, 0xd9, 0x78, 0xb8, 0xb8, 0x71, 0xaa, 0x69, 0xf7,
	0xdb, 0xf8, 0x4b, 0x74, 0x6b, 0x28, 0x0f, 0x43, 0x26, 0xaf, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xf9, 0x02, 0xcd, 0x9f, 0xbf, 0x02, 0x00, 0x00,
}
