// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: internal/shared/proto/animetosho.proto

package animetosho

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnimeToshoService_GetParsedEpisodes_FullMethodName = "/animetosho.AnimeToshoService/GetParsedEpisodes"
)

// AnimeToshoServiceClient is the client API for AnimeToshoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnimeToshoService — сервис для получения торрент-эпизодов с AnimeTosho
type AnimeToshoServiceClient interface {
	// GetParsedEpisodes — аналог GetParsedToshoEpisodes
	// Возвращает список готовых к сохранению в БД эпизодов
	GetParsedEpisodes(ctx context.Context, in *GetParsedEpisodesRequest, opts ...grpc.CallOption) (*GetParsedEpisodesResponse, error)
}

type animeToshoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnimeToshoServiceClient(cc grpc.ClientConnInterface) AnimeToshoServiceClient {
	return &animeToshoServiceClient{cc}
}

func (c *animeToshoServiceClient) GetParsedEpisodes(ctx context.Context, in *GetParsedEpisodesRequest, opts ...grpc.CallOption) (*GetParsedEpisodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParsedEpisodesResponse)
	err := c.cc.Invoke(ctx, AnimeToshoService_GetParsedEpisodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnimeToshoServiceServer is the server API for AnimeToshoService service.
// All implementations must embed UnimplementedAnimeToshoServiceServer
// for forward compatibility.
//
// AnimeToshoService — сервис для получения торрент-эпизодов с AnimeTosho
type AnimeToshoServiceServer interface {
	// GetParsedEpisodes — аналог GetParsedToshoEpisodes
	// Возвращает список готовых к сохранению в БД эпизодов
	GetParsedEpisodes(context.Context, *GetParsedEpisodesRequest) (*GetParsedEpisodesResponse, error)
	mustEmbedUnimplementedAnimeToshoServiceServer()
}

// UnimplementedAnimeToshoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnimeToshoServiceServer struct{}

func (UnimplementedAnimeToshoServiceServer) GetParsedEpisodes(context.Context, *GetParsedEpisodesRequest) (*GetParsedEpisodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParsedEpisodes not implemented")
}
func (UnimplementedAnimeToshoServiceServer) mustEmbedUnimplementedAnimeToshoServiceServer() {}
func (UnimplementedAnimeToshoServiceServer) testEmbeddedByValue()                           {}

// UnsafeAnimeToshoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnimeToshoServiceServer will
// result in compilation errors.
type UnsafeAnimeToshoServiceServer interface {
	mustEmbedUnimplementedAnimeToshoServiceServer()
}

func RegisterAnimeToshoServiceServer(s grpc.ServiceRegistrar, srv AnimeToshoServiceServer) {
	// If the following call panics, it indicates UnimplementedAnimeToshoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnimeToshoService_ServiceDesc, srv)
}

func _AnimeToshoService_GetParsedEpisodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParsedEpisodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnimeToshoServiceServer).GetParsedEpisodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnimeToshoService_GetParsedEpisodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnimeToshoServiceServer).GetParsedEpisodes(ctx, req.(*GetParsedEpisodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnimeToshoService_ServiceDesc is the grpc.ServiceDesc for AnimeToshoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnimeToshoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "animetosho.AnimeToshoService",
	HandlerType: (*AnimeToshoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetParsedEpisodes",
			Handler:    _AnimeToshoService_GetParsedEpisodes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/shared/proto/animetosho.proto",
}
