// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anilist.proto

package anilist

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Запрос
type GetAnimeInfoRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAnimeInfoRequest) Reset()         { *m = GetAnimeInfoRequest{} }
func (m *GetAnimeInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetAnimeInfoRequest) ProtoMessage()    {}
func (*GetAnimeInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33922f0fe49f418, []int{0}
}

func (m *GetAnimeInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimeInfoRequest.Unmarshal(m, b)
}
func (m *GetAnimeInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimeInfoRequest.Marshal(b, m, deterministic)
}
func (m *GetAnimeInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimeInfoRequest.Merge(m, src)
}
func (m *GetAnimeInfoRequest) XXX_Size() int {
	return xxx_messageInfo_GetAnimeInfoRequest.Size(m)
}
func (m *GetAnimeInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimeInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimeInfoRequest proto.InternalMessageInfo

func (m *GetAnimeInfoRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// Ответ
type GetAnimeInfoResponse struct {
	// Types that are valid to be assigned to Result:
	//	*GetAnimeInfoResponse_Anime
	//	*GetAnimeInfoResponse_Error
	Result               isGetAnimeInfoResponse_Result `protobuf_oneof:"result"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *GetAnimeInfoResponse) Reset()         { *m = GetAnimeInfoResponse{} }
func (m *GetAnimeInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetAnimeInfoResponse) ProtoMessage()    {}
func (*GetAnimeInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33922f0fe49f418, []int{1}
}

func (m *GetAnimeInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAnimeInfoResponse.Unmarshal(m, b)
}
func (m *GetAnimeInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAnimeInfoResponse.Marshal(b, m, deterministic)
}
func (m *GetAnimeInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAnimeInfoResponse.Merge(m, src)
}
func (m *GetAnimeInfoResponse) XXX_Size() int {
	return xxx_messageInfo_GetAnimeInfoResponse.Size(m)
}
func (m *GetAnimeInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAnimeInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAnimeInfoResponse proto.InternalMessageInfo

type isGetAnimeInfoResponse_Result interface {
	isGetAnimeInfoResponse_Result()
}

type GetAnimeInfoResponse_Anime struct {
	Anime *AnimeInfo `protobuf:"bytes,1,opt,name=anime,proto3,oneof"`
}

type GetAnimeInfoResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetAnimeInfoResponse_Anime) isGetAnimeInfoResponse_Result() {}

func (*GetAnimeInfoResponse_Error) isGetAnimeInfoResponse_Result() {}

func (m *GetAnimeInfoResponse) GetResult() isGetAnimeInfoResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetAnimeInfoResponse) GetAnime() *AnimeInfo {
	if x, ok := m.GetResult().(*GetAnimeInfoResponse_Anime); ok {
		return x.Anime
	}
	return nil
}

func (m *GetAnimeInfoResponse) GetError() *Error {
	if x, ok := m.GetResult().(*GetAnimeInfoResponse_Error); ok {
		return x.Error
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetAnimeInfoResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetAnimeInfoResponse_Anime)(nil),
		(*GetAnimeInfoResponse_Error)(nil),
	}
}

// Основная структура аниме (почти 1:1 с вашей AnimeInfo)
type AnimeInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                *Title   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Format               string   `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Episodes             int32    `protobuf:"varint,6,opt,name=episodes,proto3" json:"episodes,omitempty"`
	Duration             int32    `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	AverageScore         int32    `protobuf:"varint,8,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	Genres               []string `protobuf:"bytes,9,rep,name=genres,proto3" json:"genres,omitempty"`
	Season               string   `protobuf:"bytes,10,opt,name=season,proto3" json:"season,omitempty"`
	SeasonYear           int32    `protobuf:"varint,11,opt,name=season_year,json=seasonYear,proto3" json:"season_year,omitempty"`
	StartDate            *Date    `protobuf:"bytes,12,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	CoverImage           *Image   `protobuf:"bytes,13,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnimeInfo) Reset()         { *m = AnimeInfo{} }
func (m *AnimeInfo) String() string { return proto.CompactTextString(m) }
func (*AnimeInfo) ProtoMessage()    {}
func (*AnimeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33922f0fe49f418, []int{2}
}

func (m *AnimeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnimeInfo.Unmarshal(m, b)
}
func (m *AnimeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnimeInfo.Marshal(b, m, deterministic)
}
func (m *AnimeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnimeInfo.Merge(m, src)
}
func (m *AnimeInfo) XXX_Size() int {
	return xxx_messageInfo_AnimeInfo.Size(m)
}
func (m *AnimeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AnimeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AnimeInfo proto.InternalMessageInfo

func (m *AnimeInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AnimeInfo) GetTitle() *Title {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *AnimeInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AnimeInfo) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *AnimeInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *AnimeInfo) GetEpisodes() int32 {
	if m != nil {
		return m.Episodes
	}
	return 0
}

func (m *AnimeInfo) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *AnimeInfo) GetAverageScore() int32 {
	if m != nil {
		return m.AverageScore
	}
	return 0
}

func (m *AnimeInfo) GetGenres() []string {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *AnimeInfo) GetSeason() string {
	if m != nil {
		return m.Season
	}
	return ""
}

func (m *AnimeInfo) GetSeasonYear() int32 {
	if m != nil {
		return m.SeasonYear
	}
	return 0
}

func (m *AnimeInfo) GetStartDate() *Date {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *AnimeInfo) GetCoverImage() *Image {
	if m != nil {
		return m.CoverImage
	}
	return nil
}

type Title struct {
	Romaji               string   `protobuf:"bytes,1,opt,name=romaji,proto3" json:"romaji,omitempty"`
	English              string   `protobuf:"bytes,2,opt,name=english,proto3" json:"english,omitempty"`
	Native               string   `protobuf:"bytes,3,opt,name=native,proto3" json:"native,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Title) Reset()         { *m = Title{} }
func (m *Title) String() string { return proto.CompactTextString(m) }
func (*Title) ProtoMessage()    {}
func (*Title) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33922f0fe49f418, []int{3}
}

func (m *Title) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Title.Unmarshal(m, b)
}
func (m *Title) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Title.Marshal(b, m, deterministic)
}
func (m *Title) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Title.Merge(m, src)
}
func (m *Title) XXX_Size() int {
	return xxx_messageInfo_Title.Size(m)
}
func (m *Title) XXX_DiscardUnknown() {
	xxx_messageInfo_Title.DiscardUnknown(m)
}

var xxx_messageInfo_Title proto.InternalMessageInfo

func (m *Title) GetRomaji() string {
	if m != nil {
		return m.Romaji
	}
	return ""
}

func (m *Title) GetEnglish() string {
	if m != nil {
		return m.English
	}
	return ""
}

func (m *Title) GetNative() string {
	if m != nil {
		return m.Native
	}
	return ""
}

type Date struct {
	Year                 int32    `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=day,proto3" json:"day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33922f0fe49f418, []int{4}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type Image struct {
	Large                string   `protobuf:"bytes,1,opt,name=large,proto3" json:"large,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Image) Reset()         { *m = Image{} }
func (m *Image) String() string { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()    {}
func (*Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33922f0fe49f418, []int{5}
}

func (m *Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Image.Unmarshal(m, b)
}
func (m *Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Image.Marshal(b, m, deterministic)
}
func (m *Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Image.Merge(m, src)
}
func (m *Image) XXX_Size() int {
	return xxx_messageInfo_Image.Size(m)
}
func (m *Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Image proto.InternalMessageInfo

func (m *Image) GetLarge() string {
	if m != nil {
		return m.Large
	}
	return ""
}

type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f33922f0fe49f418, []int{6}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*GetAnimeInfoRequest)(nil), "anilist.GetAnimeInfoRequest")
	proto.RegisterType((*GetAnimeInfoResponse)(nil), "anilist.GetAnimeInfoResponse")
	proto.RegisterType((*AnimeInfo)(nil), "anilist.AnimeInfo")
	proto.RegisterType((*Title)(nil), "anilist.Title")
	proto.RegisterType((*Date)(nil), "anilist.Date")
	proto.RegisterType((*Image)(nil), "anilist.Image")
	proto.RegisterType((*Error)(nil), "anilist.Error")
}

func init() { proto.RegisterFile("anilist.proto", fileDescriptor_f33922f0fe49f418) }

var fileDescriptor_f33922f0fe49f418 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x7f, 0x6b, 0x14, 0x31,
	0x10, 0xb5, 0x77, 0x97, 0xfb, 0x31, 0x77, 0x7b, 0x4a, 0x2c, 0x12, 0x8a, 0xc5, 0x63, 0x15, 0x11,
	0x95, 0x16, 0x2a, 0x7e, 0x80, 0x1e, 0x8a, 0x16, 0xfd, 0xc7, 0xad, 0xff, 0x28, 0xc8, 0x11, 0x77,
	0xa7, 0x6b, 0x64, 0x37, 0x39, 0x93, 0xdc, 0x41, 0xbf, 0x8d, 0x1f, 0x55, 0x32, 0xc9, 0x2e, 0xb5,
	0xe8, 0x7f, 0xf3, 0xde, 0xbc, 0x9d, 0x79, 0x3b, 0x99, 0x81, 0x4c, 0x6a, 0xd5, 0x28, 0xe7, 0x4f,
	0xb6, 0xd6, 0x78, 0xc3, 0x27, 0x09, 0xe6, 0x2f, 0xe0, 0xfe, 0x3b, 0xf4, 0xe7, 0x5a, 0xb5, 0x78,
	0xa1, 0xaf, 0x4c, 0x81, 0xbf, 0x76, 0xe8, 0x3c, 0x3f, 0x04, 0xe6, 0x95, 0x6f, 0x50, 0x1c, 0xac,
	0x0e, 0x9e, 0xcd, 0x8a, 0x08, 0x72, 0x0f, 0x87, 0x7f, 0x8b, 0xdd, 0xd6, 0x68, 0x87, 0xfc, 0x39,
	0x30, 0x19, 0x48, 0x52, 0xcf, 0xcf, 0xf8, 0x49, 0xd7, 0xac, 0x97, 0xbe, 0xbf, 0x53, 0x44, 0x09,
	0x7f, 0x0a, 0x0c, 0xad, 0x35, 0x56, 0x0c, 0x48, 0xbb, 0xec, 0xb5, 0x6f, 0x03, 0x1b, 0x74, 0x94,
	0x5e, 0x4f, 0x61, 0x6c, 0xd1, 0xed, 0x1a, 0x9f, 0xff, 0x1e, 0xc2, 0xac, 0x2f, 0xc4, 0x97, 0x30,
	0x50, 0x15, 0x35, 0x62, 0xc5, 0x40, 0x55, 0xfc, 0x49, 0xe7, 0xf4, 0x76, 0xbd, 0xcf, 0x81, 0x4d,
	0xce, 0xf9, 0x0a, 0xe6, 0x15, 0xba, 0xd2, 0xaa, 0xad, 0x57, 0x46, 0x8b, 0x21, 0xfd, 0xd5, 0x4d,
	0x8a, 0x3f, 0x80, 0xf1, 0x95, 0xb1, 0xad, 0xf4, 0x62, 0x44, 0xc9, 0x84, 0x02, 0xef, 0xbc, 0xf4,
	0x3b, 0x27, 0x58, 0xe4, 0x23, 0xe2, 0x47, 0x30, 0xc5, 0xad, 0x72, 0xa6, 0x42, 0x27, 0xc6, 0xe4,
	0xa6, 0xc7, 0x21, 0x57, 0xed, 0xac, 0xa4, 0x56, 0x93, 0x98, 0xeb, 0x30, 0x7f, 0x0c, 0x99, 0xdc,
	0xa3, 0x95, 0x35, 0x6e, 0x5c, 0x69, 0x2c, 0x8a, 0x29, 0x09, 0x16, 0x89, 0xbc, 0x0c, 0x5c, 0x68,
	0x5a, 0xa3, 0xb6, 0xe8, 0xc4, 0x6c, 0x35, 0x0c, 0x4d, 0x23, 0x22, 0x33, 0x28, 0x9d, 0xd1, 0x02,
	0x92, 0x19, 0x42, 0xfc, 0x11, 0xcc, 0x63, 0xb4, 0xb9, 0x46, 0x69, 0xc5, 0x9c, 0x4a, 0x42, 0xa4,
	0xbe, 0xa0, 0xb4, 0xfc, 0x25, 0x80, 0xf3, 0xd2, 0xfa, 0x4d, 0x25, 0x3d, 0x8a, 0x05, 0x8d, 0x2a,
	0xeb, 0x47, 0xf5, 0x46, 0x7a, 0x2c, 0x66, 0x24, 0x08, 0x21, 0x3f, 0x85, 0x79, 0x69, 0xf6, 0x68,
	0x37, 0xaa, 0x95, 0x35, 0x8a, 0xec, 0xd6, 0x64, 0x2f, 0x02, 0x5b, 0x00, 0x49, 0x28, 0xce, 0x3f,
	0x01, 0xa3, 0x71, 0x07, 0x83, 0xd6, 0xb4, 0xf2, 0xa7, 0x4a, 0x8b, 0x93, 0x10, 0x17, 0x30, 0x41,
	0x5d, 0x37, 0xca, 0xfd, 0xa0, 0x77, 0x9a, 0x15, 0x1d, 0x0c, 0x5f, 0x68, 0xe9, 0xd5, 0x1e, 0xd3,
	0xa3, 0x24, 0x94, 0xaf, 0x61, 0x44, 0x5e, 0x38, 0x8c, 0xe8, 0x9f, 0xe2, 0x8b, 0x53, 0x1c, 0xb6,
	0xb3, 0x35, 0xda, 0xc7, 0x5a, 0xac, 0x88, 0x80, 0xdf, 0x83, 0x61, 0x25, 0xaf, 0xa9, 0x0c, 0x2b,
	0x42, 0x98, 0x1f, 0x03, 0x23, 0x7f, 0xe1, 0x83, 0x46, 0xda, 0xba, 0x5f, 0x67, 0x02, 0xf9, 0x6b,
	0x60, 0xb4, 0x74, 0xc1, 0x5d, 0x8b, 0xce, 0xc9, 0x5e, 0xd0, 0xc1, 0xd0, 0xbd, 0x34, 0x15, 0xa6,
	0x46, 0x14, 0x9f, 0x7d, 0x83, 0xe5, 0xb9, 0x56, 0x1f, 0x95, 0xf3, 0x97, 0x68, 0xf7, 0xaa, 0x44,
	0xfe, 0x01, 0x16, 0x37, 0xef, 0x82, 0x3f, 0xec, 0x47, 0xf5, 0x8f, 0xdb, 0x3a, 0x3a, 0xfe, 0x4f,
	0x36, 0x1e, 0xd3, 0xfa, 0xee, 0xd7, 0x8c, 0x6e, 0xf4, 0x34, 0xa9, 0xbe, 0x8f, 0x09, 0xbe, 0xfa,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x24, 0xe2, 0x96, 0xf9, 0xc3, 0x03, 0x00, 0x00,
}
