// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.6.1
// source: anilist.proto

package anilist

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AniListService_GetAnimeInfo_FullMethodName = "/anilist.AniListService/GetAnimeInfo"
)

// AniListServiceClient is the client API for AniListService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AniListService — основной сервис для работы с AniList API
type AniListServiceClient interface {
	// GetAnimeInfo — получает информацию об аниме по названию (аналог GetAnilistAnimeInfo)
	GetAnimeInfo(ctx context.Context, in *GetAnimeInfoRequest, opts ...grpc.CallOption) (*GetAnimeInfoResponse, error)
}

type aniListServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAniListServiceClient(cc grpc.ClientConnInterface) AniListServiceClient {
	return &aniListServiceClient{cc}
}

func (c *aniListServiceClient) GetAnimeInfo(ctx context.Context, in *GetAnimeInfoRequest, opts ...grpc.CallOption) (*GetAnimeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnimeInfoResponse)
	err := c.cc.Invoke(ctx, AniListService_GetAnimeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AniListServiceServer is the server API for AniListService service.
// All implementations must embed UnimplementedAniListServiceServer
// for forward compatibility.
//
// AniListService — основной сервис для работы с AniList API
type AniListServiceServer interface {
	// GetAnimeInfo — получает информацию об аниме по названию (аналог GetAnilistAnimeInfo)
	GetAnimeInfo(context.Context, *GetAnimeInfoRequest) (*GetAnimeInfoResponse, error)
	mustEmbedUnimplementedAniListServiceServer()
}

// UnimplementedAniListServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAniListServiceServer struct{}

func (UnimplementedAniListServiceServer) GetAnimeInfo(context.Context, *GetAnimeInfoRequest) (*GetAnimeInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnimeInfo not implemented")
}
func (UnimplementedAniListServiceServer) mustEmbedUnimplementedAniListServiceServer() {}
func (UnimplementedAniListServiceServer) testEmbeddedByValue()                        {}

// UnsafeAniListServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AniListServiceServer will
// result in compilation errors.
type UnsafeAniListServiceServer interface {
	mustEmbedUnimplementedAniListServiceServer()
}

func RegisterAniListServiceServer(s grpc.ServiceRegistrar, srv AniListServiceServer) {
	// If the following call panics, it indicates UnimplementedAniListServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AniListService_ServiceDesc, srv)
}

func _AniListService_GetAnimeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnimeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AniListServiceServer).GetAnimeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AniListService_GetAnimeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AniListServiceServer).GetAnimeInfo(ctx, req.(*GetAnimeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AniListService_ServiceDesc is the grpc.ServiceDesc for AniListService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AniListService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anilist.AniListService",
	HandlerType: (*AniListServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAnimeInfo",
			Handler:    _AniListService_GetAnimeInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anilist.proto",
}
